# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5432'
    volumes:
      - photos-db:/var/lib/postgresql/data

  photos:
    build:
      context: .
    environment:
      UI_NAME: user
      UI_EMAIL: user@gmail.com
      UI_PASSWORD: 0123456789
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    expose:
      - '3000'
    links:
      - postgres
    volumes:
      - ./media/photos:/photos
      - ./media/thumbnails:/thumbnails

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/photos.conf
      - ./media/thumbnails:/thumbnails
    ports:
      - 3333:3333
    depends_on:
      - photos
    links:
      - photos

volumes:
  photos-db:
