# docker-compose.yml

version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5432'
    volumes:
      - photos-db:/var/lib/postgresql/data

  photos:
    container_name: photos
    build:
      context: ./nodejs
    environment:
      UI_NAME: ${NAME}
      UI_EMAIL: ${EMAIL}
      UI_PASSWORD: ${PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      BACKUPS_DIR: /backups
      MEDIA_DIR: /photos
      THUMBNAILS_DIR: /thumbnails
    depends_on:
      - postgres
    links:
      - postgres
    expose:
      - '3000'
    volumes:
      - ${PHOTOS_DIR}:/photos
      - ${THUMBNAILS_DIR}:/thumbnails
      - ${BACKUPS_DIR}:/backups

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    environment:
      PUBLIC_PATH: '/'
      HISTORY_MODE: 'true'
    ports:
      - 3333:${API_PORT}
      - 80:${WEB_PORT}
    depends_on:
      - photos
    links:
      - photos
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${THUMBNAILS_DIR}:/thumbnails

volumes:
  photos-db:
