# docker-compose.yml

version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5432'
    volumes:
      - photos-db:/var/lib/postgresql/data

  photos:
    container_name: photos
    build:
      context: ./nodejs
    environment:
      UI_NAME: user
      UI_EMAIL: user@gmail.com
      UI_PASSWORD: 0123456789
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      BACKUPS_DIR: /backups
      MEDIA_DIR: /photos
      THUMBNAILS_DIR: /thumbnails
    depends_on:
      - postgres
    links:
      - postgres
    expose:
      - '3000'
    volumes:
      - ./media/photos:/photos
      - ./media/thumbnails:/thumbnails
      - ./media/db-backups:/backups

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    environment:
      PUBLIC_PATH: '/'
      HISTORY_MODE: 'true'
    ports:
      - 3333:3333
      - 80:80
    depends_on:
      - photos
    links:
      - photos
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/photos.conf
      - ./media/thumbnails:/thumbnails

volumes:
  photos-db:
