# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - photos-db:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3333:3333
    networks:
      - backend

  ruurd-photos:
    build:
      context: .
    environment:
      UI_NAME: user
      UI_EMAIL: user@gmail.com
      UI_PASSWORD: 0123456789
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    expose:
      - '3000'
    networks:
      - backend
    volumes:
      - ./testtest:/photos

volumes:
  photos-db:
networks:
  backend:
