[package]
name = "generate_thumbnails"
version = "0.1.0"
edition = "2024"

[dependencies]
app_state = { path = "../../libs/app_state" }
tokio = { version = "1.47.1", features = ["full"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
temp-dir = "0.2.0"
color-eyre = "0.6.5"
ravif = { version = "0.13.0", features = ["asm"] }
rayon = "1.11.0"
image = { version = "0.25.8", features = ["jpeg", "png", "gif"] }
fast_image_resize = { version = "6.0.0", features = ["image"] }
rgb = "0.8"
imgref = "1.12.0"
walkdir = "2.5.0"
libheif-rs = "2.7.0"
panorama-tiler = "0.1.1"
tracing = "0.1.44"
exiftool = "0.3.1"

[dev-dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
dotenvy = "0.15.7"
tracing-subscriber = "0.3.18"