[package]
name = "photos_app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "photos_app"
path = "src/main.rs"

[dependencies]
api = { path = "../api" }
worker_scaler = { path = "../worker_scaler" }
watcher = { path = "../watcher" }
model_provider = { path = "../../libs/model_provider" }
app_state = { path = "../../libs/app_state" }
common_services = { path = "../../libs/common_services" }
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
color-eyre = "0.6.5"
tracing = "0.1.41"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-native-tls", "postgres", "chrono", "macros", "json", "uuid"] }

[features]
load-dynamic = [
    "api/load-dynamic",
    "worker_scaler/load-dynamic",
    "watcher/load-dynamic",
    "model_provider/load-dynamic",
    "common_services/load-dynamic"
]