[package]
name = "worker_scaler"
version = "0.1.0"
edition = "2024"

[dependencies]
app_state = { path = "../../libs/app_state" }
common_services = { path = "../../libs/common_services" }
model_provider = { path = "../../libs/model_provider" }
worker = { path = "../worker" }
media_analyzer = "0.10.4"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-native-tls", "postgres", "chrono", "macros", "json"] }
tokio = { version = "1.47.1", features = ["full"] }
color-eyre = "0.6.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
sysinfo = "0.33.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
ort = { version = "2.0.0-rc.12" }

[features]
load-dynamic = [
    "worker/load-dynamic",
    "common_services/load-dynamic",
    "model_provider/load-dynamic",
    "ort/load-dynamic"
]