ingest:
  media_folder: C:\Users\Ruurd\Pictures\media_dir
  app_data_folder: app_data
  enable_cache: true

  analyzer:
    llm_base_url: "http://localhost:8080"
    search:
      embedder_model_id: RuteNL/MobileCLIP2-S3-OpenCLIP-ONNX
      semantic_score_threshold: 0.8
      semantic_weight: 0.5
      text_weight: 0.5
    analyze_image_size: 720
    theme_generation:
      variant: Vibrant

  file_detection:
    video_extensions:
      - "mp4"
      - "webm"
      - "av1"
      - "3gp"
      - "mov"
      - "mkv"
      - "flv"
      - "m4v"
      - "m4p"
    photo_extensions:
      - "jpg"
      - "jpeg"
      - "png"
      - "gif"
      - "tiff"
      - "tga"
      - "avif"
      - "heic"
      - "heif"

  thumbnails:
    recreate_if_exists: false
    heights:
      - 144
      - 240
      - 360
      - 480
      - 720
      - 1080
      - 1440
    thumbnail_extension: "avif"
    avif_options:
      quality: 80
      alpha_quality: 80
      speed: 4
    video_options:
      extension: "webm"
      thumb_time: 0.5
      percentages:
        - 0
        - 33
        - 66
        - 99
      height: 720
      transcode_outputs:
        - height: 480
          quality: 35
        - height: 144
          quality: 40

logging:
  level: "info"

api:
  host: "0.0.0.0"
  port: 9475
  allowed_origins:
    - "http://localhost:5173"
    - "https://localhost:5173"
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "https://ruurdbijlsma.github.io"
  public_url: "http://localhost:9475"
  rate_limiting:
    req_per_second: 6
    burst_size: 10

secrets:
  jwt: "overwrite-me-with-env"

constants:
  allow_file_modifications: true
  allow_file_deletion: true
  fallback_timezone: Europe/Amsterdam
  onboarding_n_media_samples: 8
  
  database:
    max_connections: 20
    min_connection: 3
    max_lifetime: 1800
    idle_timeout: 600
    acquire_timeout: 30
    media_item_id_length: 10
    album_id_length: 10

  auth:
    access_token_expiry_minutes: 30
    refresh_token_expiry_days: 7
    album_invitation_expiry_minutes: 1440 # 24 hours

daily_cards:
  cluster:
    min_cards: 1
    max_cards: 3
  estimatr:
    rounds_per_day: 3