[package]
name = "common_types"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-native-tls", "postgres", "chrono", "macros", "json", "uuid"] }
serde = { version = "1.0.228", features = ["derive"] }
prost = "0.14.3"
url = "2.5.7"
face_id = "0.4.0"
object_detector = { version = "0.5.0" }

[build-dependencies]
prost-build = "0.14.3"
protox = { version = "0.9.1" }

[features]
load-dynamic = ["face_id/load-dynamic", "object_detector/load-dynamic"] # -> Load ONNXRuntime dynamically instead of statically