name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build-and-test:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cache and install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libfontconfig1-dev pkg-config exiftool protobuf-compiler nasm postgresql-client libheif-dev
          version: 1.1

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --no-deps -- -D clippy::all -D clippy::pedantic -D clippy::nursery

      - name: Build
        run: cargo build
